INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-1, 'jdoe', 'John', 'Doe');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-2, 'emuster', 'Erika', 'Mustermann');
INSERT INTO USERS (ID, USERNAME, FIRSTNAME, LASTNAME) VALUES (-3, 'ionel', 'Ionel', 'Tester'); 